// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZNMiZlTazI-yi8yaWV-IE8u1FLy3Vmug',
    appId: '1:508216365276:web:e413fd2ef2602356f56419',
    messagingSenderId: '508216365276',
    projectId: 'atv5-entrega',
    authDomain: 'atv5-entrega.firebaseapp.com',
    databaseURL: 'https://atv5-entrega-default-rtdb.firebaseio.com',
    storageBucket: 'atv5-entrega.firebasestorage.app',
    measurementId: 'G-E78YLH01V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl-8AyDleDfw9bUGYpsqEMlJh-6lZajxE',
    appId: '1:508216365276:android:86389b0e133dfc38f56419',
    messagingSenderId: '508216365276',
    projectId: 'atv5-entrega',
    databaseURL: 'https://atv5-entrega-default-rtdb.firebaseio.com',
    storageBucket: 'atv5-entrega.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ZRepc4jm9eTeo-mgEy_JvbPkaH-bBhQ',
    appId: '1:508216365276:ios:4a90101cc57f7406f56419',
    messagingSenderId: '508216365276',
    projectId: 'atv5-entrega',
    databaseURL: 'https://atv5-entrega-default-rtdb.firebaseio.com',
    storageBucket: 'atv5-entrega.firebasestorage.app',
    iosBundleId: 'com.example.atv5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ZRepc4jm9eTeo-mgEy_JvbPkaH-bBhQ',
    appId: '1:508216365276:ios:4a90101cc57f7406f56419',
    messagingSenderId: '508216365276',
    projectId: 'atv5-entrega',
    databaseURL: 'https://atv5-entrega-default-rtdb.firebaseio.com',
    storageBucket: 'atv5-entrega.firebasestorage.app',
    iosBundleId: 'com.example.atv5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZNMiZlTazI-yi8yaWV-IE8u1FLy3Vmug',
    appId: '1:508216365276:web:e3f1e3c43793b709f56419',
    messagingSenderId: '508216365276',
    projectId: 'atv5-entrega',
    authDomain: 'atv5-entrega.firebaseapp.com',
    databaseURL: 'https://atv5-entrega-default-rtdb.firebaseio.com',
    storageBucket: 'atv5-entrega.firebasestorage.app',
    measurementId: 'G-MCE09KB0W4',
  );
}
